export const userConstants = {
  REGISTER_REQUEST: "USER_REGISTER_REQUEST",
  REGISTER_SUCCES: "USER_REGISTER_SUCCES",
  REGISTER_FAILURE: "USER_REGISTER_FAILURE",

  LOGIN_REQUEST: "USER_LOGIN_REQUEST",
  LOGIN_SUCCES: "USER_LOGIN_SUCCES",
  LOGIN_FAILURE: "USER_LOGIN_FAILURE",

  LOGOUT: "USERS_LOGOUT",

  GETALL_REQUEST: "USERS_GETALL_REQUEST",
  GETALL_SUCCESS: "USERS_GETALL_SUCCESS",
  GETALL_FAILURE: "USERS_GETALL_FAILURE",

  DELETE_REQUEST: "USERS_DELETE_REQUEST",
  DELETE_SUCCESS: "USERS_DELETE_SUCCESS",
  DELETE_FAILURE: "USERS_DELETE_FAILURE"
};
